scripts/capture/capture.sh

The ‘.gz’ file extension is not needed in the `tcpdump` command: Gzip will automatically add that when compressing the plain ‘.pcap’ file.
The `tcpdump` filter should be wrapped with double quotes. With single quotes bash can’t evaluate variables inside the filter specification (at least this happens with my bash, version 4.3.42).

Capture script fix

---

scripts/run/config.sh

In file `$ENTRADA_HOME/scripts/run/config.sh` the variable `ENTRADA_JAR` is set to `“entrada-0.0.2-jar-with-dependencies.jar”`, but the correct name for the JAR file is `"pcap-to-parquet-0.0.2-jar-with-dependencies.jar"`.

Fixing jar filename in config file

---

scripts/run/config.sh

This patch checks the directories in DATA_RSYNC_DIR and adds them as list to the NAMESERVERS-variable in config.sh

config.sh: autodetect NAMESERVERS

---

pcap-to-parquet/pom.xml
pcap-to-parquet/src/main/java/nl/sidn/pcap/parquet/DNSParquetPacketWriter.java
pcap-to-parquet/src/main/java/nl/sidn/pcap/parquet/ICMPParquetPacketWriter.java
pcap-to-parquet/src/main/resources/dns-query.avsc
pcap-to-parquet/src/main/resources/icmp-packet.avsc
scripts/database/create-table-dns-queries.sql
scripts/database/create-table-dns-staging.sql
scripts/database/create-table-icmp-packets.sql
scripts/database/create-table-icmp-staging.sql
scripts/run/run_03_staging_to_warehouse.sh

This patch add 2 additional columns "server_ns_name" and "server_location" to the database schema. This allows to store the location of anycast-nodes. If the servername (as defined in NAMESERVERS) contains a "_", it is assumed that the part before the "_" is the anycast_server name and the part after the "_" is the location of the server f.e. r.ns.at_vie  sets "server_ns_name" to "r.ns.at" and "server_location_location" to "vie". The original svr/server fields remain untouched.

store server location

---

pcap-to-parquet/src/main/java/nl/sidn/pcap/util/Settings.java

the broken labelCount caused a wrong mapping from qname to domainname when using tld.suffix. 
"foo.test.co.at" has been mapped "co.co.at" instead of "test.co.at" (tld.suffix=.co.at)

fix handling of tld.suffix

---

scripts/database/create-table-dns-queries.sql
scripts/database/create-table-dns-staging.sql
scripts/database/create-table-icmp-packets.sql
scripts/database/create-table-icmp-staging.sql
scripts/install/create_impala_tables.sh
scripts/run/config.sh
scripts/run/run_02_partial_loader.sh
scripts/run/run_03_staging_to_warehouse.sh
scripts/run/run_05_update_stats_staging.sh

This patch  allows the use of multiple tables with different config files (e.g. to load a possible broken pcap file into a temporary table or load traces from different TLDs into the same hadoop cluster)

move table name declaration to config.sh

---

scripts/database/create-table-dns-queries.sql
scripts/database/create-table-dns-staging.sql
scripts/database/create-table-icmp-packets.sql
scripts/database/create-table-icmp-staging.sql
scripts/install/create_impala_tables.sh
scripts/run/config.sh

this patches uses the variables defined in config.sh for the HDFS location of the tables (forgot this in my previous patch, sorry).

fixed HDFS_LOCATION for the tables (set it in config.sh)

---

pcap-to-parquet/src/main/java/nl/sidn/pcap/load/LoaderThread.java

this should speedup the processes when (re)loading a lot of files

check every 100ms instead of 5s if queue is empty

---

scripts/run/run_03_staging_to_warehouse.sh

currently, when kerberos authentication is disabled, ```run_03_staging_to_warehouse.sh``` fails with ```-k requires a valid kerberos ticket but no valid kerberos ticket found.``` , because the ```-k``` option is passed to impala anyway
also the check if kerberos options should be passed always returns true  if ```KEYTAB_FILE``` is set to the empty string in ```config.sh```
This commit should fix both issues.

Fix kerberos opts in run_03_staging_to_warehouse.sh

---

scripts/install/create_impala_tables.sh
scripts/run/run_02_partial_loader.sh
scripts/run/run_05_update_stats_staging.sh

In PR #40  I didn't realize that  $KEYTAB_FILE being empty causes errors in other scripts as well. This PR adds similar checks in run02/run05 and create_impala_tables
in create_impala_tables line 60 (line 63 after the change), '-k' wasn't passed before. I'm not sure if this was a bug or intended. If this was intended then we probably should not pass '$IMPALA_OPTS' here

Fix more kerberos opt handling

---

dnslib4java/src/main/java/nl/sidn/dnslib/message/records/dnssec/DNSKEYResourceRecord.java
dnslib4java/src/main/java/nl/sidn/dnslib/util/KeyUtil.java

Tried to fix the ECDSA issue. Actually, to clarify: the RuntimeException title was maybe slightly confusing, since the RuntimeException got catched within the code and just resulted in a log entry saying something about 'Error creating public key'. I ran the code on 1 pcap file and everything seemed to work fine. There where slightly more parsed packets than in the original version, since the ones having ECDSA DNS keys did not get ignored.

fixed issue #56 ECDSA RuntimeException

---

.gitignore
dnslib4java/src/main/java/nl/sidn/dnslib/types/RcodeType.java
dnslib4java/src/main/java/nl/sidn/dnslib/types/ResourceRecordType.java

Noticed that dnslib4java was missing the following RR TYPEs:
53 - SMIMEA [RFC8162]
60 - CDNSKEY [RFC7344]
61 - OPENPGPKEY [RFC7929]
62 - CSYNC [RFC7477]
258 - AVC
259 - DOA
As well as the BADCOOKIE (23) RCODE. [RFC7873].
Added them & updated the comment blocks to match.

Add missing RR TYPEs & RCODE to dnslib4java

---

dnslib4java/src/main/java/nl/sidn/dnslib/message/util/NetworkData.java

Fixes #72 by padding the buffer array to an even number of bytes, if necessary.
[This anonymized PCAP](https://github.com/SIDN/entrada/files/2129024/BadPacket-Anon.zip) contains a single packet that will cause an exception to be thrown.

Fix ArrayIndexOutOfBoundsException in NetworkData

---

pcap-to-parquet/src/main/java/nl/sidn/pcap/load/LoaderThread.java

use java.nio.file.Files move method instead of java.io.file renameTo for archiving pcap files so that it doesn't cause an error when trying to transfer across disks.

Fix archiving to work across disks

---

pcap-to-parquet/src/main/java/nl/sidn/pcap/parquet/DNSParquetPacketWriter.java
pcap-to-parquet/src/main/java/nl/sidn/pcap/util/GeoLookupUtil.java
pcap-to-parquet/src/test/java/nl/sidn/pcap/util/GeoLookupUtilTest.java

Hola SIDN,
I am not sure this is a bug and I wanted your input on this one.
There is this lookupASN function in GeoLookupUtil returning the ASN number given a certain IP, using the Maxmind DB. This function is overloaded with different representation of an IP, including a bit array representation.
Ultimately, the IP is is transformed to a InetAddress using Guava. For the byte array representation, you considered the bit representation being little endian for IP. (see InetAddresses.fromLittleEndianByteArray(ip))
I did not investigate until the pcap is read and transformed to an object and if the bit representation was big or little endian; However i see that InetAddress returns a big endian representation of the IP and so at the end, by reading little endian and return big endian you might …

IP byte[] representation

---

pcap-to-parquet/pom.xml
pcap-to-parquet/src/test/java/nl/sidn/pcap/util/GeoLookupUtilTest.java

This way everyone can run the "mvn package" without changing the code.
(after downloading maxmind files in $HOME/sidn/development/tmp/entrada/maxmind)

avoid hard-coded path in GeoLookupUtilTest

---

src/main/java/nl/sidnlabs/entrada/initialize/AmazonInitializer.java
src/main/resources/application.properties

Fe, we don't give the app runtime rights to create such resources; but manage infrastructure-as-code at deploy time

make S3 bucket and lifecycle rule management conditional

---

pom.xml

current version had an older flyway library which was not compatible with more recent postgres versions

upgrade spring boot

---

src/main/java/nl/sidnlabs/entrada/load/PacketProcessor.java
src/main/java/nl/sidnlabs/entrada/metric/HistoricalMetricManager.java

With graphite export enabled it will go over the metrics, push them and truncate the cache afterwards.
However, if you disable graphite export the send/flush is conditional; but collecting metrics isn't, nor is clearing them from time to time. This creates an OOM after a while.

clear metriccache if graphite export is disabled, to avoid OOM

---

src/main/java/nl/sidnlabs/entrada/ScheduledExecution.java
src/main/java/nl/sidnlabs/entrada/enrich/geoip/GeoIPServiceImpl.java

* check for MaxMind DB refresh when threshold is exceeded at runtime
* Legal compliance: MaxMind new regulation only allows you to keep/use the DB up til 30 days
* Refresh in case of long running app?
* as minimal change, without doing a refactor of the class

check for maxmind DB age / refresh

---

src/main/java/nl/sidnlabs/entrada/enrich/resolver/AbstractResolverCheck.java

* Lazy fix for now, clear the array
* Perhaps only-add to array if new? (but what if subnets get removed from source, they should also be removed from array .. although those sources are probably not that likely to have such changes)

pub resolver arrays got appended every time creating a leak

---

src/main/java/nl/sidnlabs/entrada/engine/AbstractQueryEngine.java
src/main/java/nl/sidnlabs/entrada/engine/LocalQueryEngine.java
src/main/java/nl/sidnlabs/entrada/engine/QueryEngine.java
src/main/java/nl/sidnlabs/entrada/service/UploadService.java

it was assumed on various places that the DNS table was called "dns"; and icmp table "icmp"; while they are configurable.
Bumped into it by accident since our pcap-to-athena fork used a different table name

differentiate table name from table type, since it is configurable

---

src/main/java/nl/sidnlabs/entrada/enrich/resolver/AbstractResolverCheck.java
src/main/java/nl/sidnlabs/entrada/initialize/AbstractInitializer.java
src/main/java/nl/sidnlabs/entrada/load/StateManager.java
src/main/resources/application.properties

to separate the volatile from the non-volatile data (allow for IO optimisation / mountpoints)

Create separate persistency subdir

---

src/main/resources/application.properties

Fix for the "impala timeout error" when user update ENTRADA from older versions and isn't using SSL. On the ENTRADA website, the default value for IMPALA_SSL is 0.

default impala.ssl value changed
